[2025-05-23T06:36:05.944+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T17:30:00+00:00 [queued]>
[2025-05-23T06:36:05.952+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T17:30:00+00:00 [queued]>
[2025-05-23T06:36:05.952+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-23T06:36:05.968+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Transform_Data> on 2025-05-22 17:30:00+00:00
[2025-05-23T06:36:05.972+0000] {standard_task_runner.py:57} INFO - Started process 7603 to run task
[2025-05-23T06:36:05.975+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Transform_Data', 'scheduled__2025-05-22T17:30:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmpyqeliw70']
[2025-05-23T06:36:05.978+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask Transform_Data
[2025-05-23T06:36:06.032+0000] {task_command.py:416} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Transform_Data scheduled__2025-05-22T17:30:00+00:00 [running]> on host 2d3af573cb97
[2025-05-23T06:36:06.096+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Scheduler_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Transform_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T17:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T17:30:00+00:00'
[2025-05-23T06:36:06.098+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-23T06:36:06.100+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Transform_Data.py']
[2025-05-23T06:36:06.109+0000] {subprocess.py:86} INFO - Output:
[2025-05-23T06:36:07.855+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-23T06:36:07.856+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-23T06:36:07.857+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-23T06:36:07.857+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-23T06:36:07.858+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-23T06:36:08.009+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-23T06:36:08.099+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-23T06:36:08.100+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-23T06:36:08.107+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-23T06:36:08.109+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-fe01714a-cc10-4f20-948b-e76c66933c13;1.0
[2025-05-23T06:36:08.110+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-23T06:36:08.216+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-23T06:36:08.249+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-23T06:36:08.271+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 154ms :: artifacts dl 8ms
[2025-05-23T06:36:08.272+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-23T06:36:08.273+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-23T06:36:08.274+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-23T06:36:08.274+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-23T06:36:08.275+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-23T06:36:08.281+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-23T06:36:08.284+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-23T06:36:08.284+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-23T06:36:08.285+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-23T06:36:08.285+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-fe01714a-cc10-4f20-948b-e76c66933c13
[2025-05-23T06:36:08.286+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-23T06:36:08.289+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 2 already retrieved (0kB/11ms)
[2025-05-23T06:36:08.548+0000] {subprocess.py:93} INFO - 25/05/23 06:36:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-23T06:36:08.871+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-23T06:36:08.872+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-23T06:36:08.873+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-23T06:36:09.854+0000] {subprocess.py:93} INFO - 25/05/23 06:36:09 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-05-23T06:36:17.556+0000] {subprocess.py:93} INFO - [Stage 1:>                                                        (0 + 13) / 13][Stage 1:====>                                                    (1 + 12) / 13]                                                                                25/05/23 06:36:17 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2025-05-23T06:36:29.098+0000] {subprocess.py:93} INFO - [Stage 2:>                                                        (0 + 13) / 13][Stage 2:====>                                                    (1 + 12) / 13][Stage 2:======================>                                   (5 + 8) / 13]                                                                                [Stage 4:>                (0 + 13) / 13][Stage 7:>                 (0 + 7) / 13][Stage 4:=>               (1 + 12) / 13][Stage 7:>                 (0 + 8) / 13][Stage 7:>                                                        (0 + 13) / 13][Stage 5:>               (10 + 9) / 200][Stage 7:==>              (2 + 11) / 13][Stage 5:=>             (17 + 15) / 200][Stage 7:=========>        (7 + 6) / 13][Stage 5:=>             (25 + 15) / 200][Stage 7:===========>      (8 + 5) / 13][Stage 5:==>            (35 + 15) / 200][Stage 7:===========>      (8 + 5) / 13][Stage 5:====>          (56 + 17) / 200][Stage 7:=============>   (10 + 3) / 13][Stage 5:======================>                                (80 + 21) / 200][Stage 5:============================>                         (107 + 30) / 200][Stage 5:========================================>             (151 + 21) / 200][Stage 8:>                                                          (0 + 1) / 1]                                                                                25/05/23 06:36:29 ERROR FileFormatWriter: Aborting job 2efa3c8f-8831-42ab-9873-491c58af70a8.
[2025-05-23T06:36:29.101+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: File file:/opt/***/data/_tmp_output/_temporary/0/task_202505230636204729460656149115122_0008_m_000000/part-00000-4d65ef59-2aae-4d72-a256-edf40eb8f0f4-c000.csv does not exist
[2025-05-23T06:36:29.102+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:666)
[2025-05-23T06:36:29.103+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:987)
[2025-05-23T06:36:29.103+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:656)
[2025-05-23T06:36:29.103+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:386)
[2025-05-23T06:36:29.104+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:337)
[2025-05-23T06:36:29.104+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.rename(RawLocalFileSystem.java:397)
[2025-05-23T06:36:29.104+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.ChecksumFileSystem.rename(ChecksumFileSystem.java:617)
[2025-05-23T06:36:29.104+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.io.ProxyLocalFileSystem.rename(ProxyLocalFileSystem.java:34)
[2025-05-23T06:36:29.105+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.mergePaths(FileOutputCommitter.java:472)
[2025-05-23T06:36:29.105+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.mergePaths(FileOutputCommitter.java:486)
[2025-05-23T06:36:29.105+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJobInternal(FileOutputCommitter.java:403)
[2025-05-23T06:36:29.105+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJob(FileOutputCommitter.java:375)
[2025-05-23T06:36:29.106+0000] {subprocess.py:93} INFO - 	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.commitJob(HadoopMapReduceCommitProtocol.scala:182)
[2025-05-23T06:36:29.106+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:220)
[2025-05-23T06:36:29.106+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:188)
[2025-05-23T06:36:29.107+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:108)
[2025-05-23T06:36:29.107+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:106)
[2025-05-23T06:36:29.107+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:131)
[2025-05-23T06:36:29.107+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
[2025-05-23T06:36:29.108+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
[2025-05-23T06:36:29.108+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-23T06:36:29.108+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
[2025-05-23T06:36:29.109+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
[2025-05-23T06:36:29.109+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
[2025-05-23T06:36:29.109+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
[2025-05-23T06:36:29.109+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
[2025-05-23T06:36:29.110+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
[2025-05-23T06:36:29.110+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
[2025-05-23T06:36:29.110+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
[2025-05-23T06:36:29.110+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
[2025-05-23T06:36:29.111+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
[2025-05-23T06:36:29.111+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
[2025-05-23T06:36:29.111+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
[2025-05-23T06:36:29.111+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
[2025-05-23T06:36:29.112+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)
[2025-05-23T06:36:29.112+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:979)
[2025-05-23T06:36:29.112+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-23T06:36:29.113+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-23T06:36:29.113+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-23T06:36:29.113+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-23T06:36:29.113+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-23T06:36:29.114+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-23T06:36:29.114+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-23T06:36:29.114+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-23T06:36:29.114+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-23T06:36:29.115+0000] {subprocess.py:93} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2025-05-23T06:36:29.115+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-23T06:36:29.146+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-23T06:36:29.147+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/Transform_Data.py", line 80, in <module>
[2025-05-23T06:36:29.151+0000] {subprocess.py:93} INFO -     Crash_Data.coalesce(1).write.mode("overwrite").option("header", "true").csv(tmp_path)
[2025-05-23T06:36:29.151+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 1372, in csv
[2025-05-23T06:36:29.152+0000] {subprocess.py:93} INFO -     self._jwrite.csv(path)
[2025-05-23T06:36:29.152+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1304, in __call__
[2025-05-23T06:36:29.153+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-23T06:36:29.153+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^
[2025-05-23T06:36:29.154+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 111, in deco
[2025-05-23T06:36:29.154+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-23T06:36:29.154+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2025-05-23T06:36:29.155+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/protocol.py", line 326, in get_return_value
[2025-05-23T06:36:29.155+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-23T06:36:29.156+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o180.csv.
[2025-05-23T06:36:29.156+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted.
[2025-05-23T06:36:29.157+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:231)
[2025-05-23T06:36:29.157+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:188)
[2025-05-23T06:36:29.158+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:108)
[2025-05-23T06:36:29.158+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:106)
[2025-05-23T06:36:29.159+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:131)
[2025-05-23T06:36:29.159+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
[2025-05-23T06:36:29.159+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
[2025-05-23T06:36:29.160+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-23T06:36:29.160+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
[2025-05-23T06:36:29.160+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
[2025-05-23T06:36:29.161+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
[2025-05-23T06:36:29.161+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
[2025-05-23T06:36:29.161+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
[2025-05-23T06:36:29.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
[2025-05-23T06:36:29.162+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
[2025-05-23T06:36:29.163+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
[2025-05-23T06:36:29.163+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
[2025-05-23T06:36:29.163+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
[2025-05-23T06:36:29.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
[2025-05-23T06:36:29.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
[2025-05-23T06:36:29.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
[2025-05-23T06:36:29.165+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)
[2025-05-23T06:36:29.165+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:979)
[2025-05-23T06:36:29.165+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-23T06:36:29.166+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-23T06:36:29.166+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-23T06:36:29.167+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-23T06:36:29.167+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-23T06:36:29.167+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-23T06:36:29.168+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-23T06:36:29.168+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-23T06:36:29.168+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-23T06:36:29.169+0000] {subprocess.py:93} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2025-05-23T06:36:29.169+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-23T06:36:29.169+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File file:/opt/***/data/_tmp_output/_temporary/0/task_202505230636204729460656149115122_0008_m_000000/part-00000-4d65ef59-2aae-4d72-a256-edf40eb8f0f4-c000.csv does not exist
[2025-05-23T06:36:29.170+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:666)
[2025-05-23T06:36:29.170+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:987)
[2025-05-23T06:36:29.171+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:656)
[2025-05-23T06:36:29.171+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:386)
[2025-05-23T06:36:29.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:337)
[2025-05-23T06:36:29.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.rename(RawLocalFileSystem.java:397)
[2025-05-23T06:36:29.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.ChecksumFileSystem.rename(ChecksumFileSystem.java:617)
[2025-05-23T06:36:29.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.io.ProxyLocalFileSystem.rename(ProxyLocalFileSystem.java:34)
[2025-05-23T06:36:29.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.mergePaths(FileOutputCommitter.java:472)
[2025-05-23T06:36:29.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.mergePaths(FileOutputCommitter.java:486)
[2025-05-23T06:36:29.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJobInternal(FileOutputCommitter.java:403)
[2025-05-23T06:36:29.174+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJob(FileOutputCommitter.java:375)
[2025-05-23T06:36:29.174+0000] {subprocess.py:93} INFO - 	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.commitJob(HadoopMapReduceCommitProtocol.scala:182)
[2025-05-23T06:36:29.174+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:220)
[2025-05-23T06:36:29.175+0000] {subprocess.py:93} INFO - 	... 33 more
[2025-05-23T06:36:29.175+0000] {subprocess.py:93} INFO - 
[2025-05-23T06:36:29.697+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-23T06:36:29.719+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-23T06:36:29.724+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Transform_Data, execution_date=20250522T173000, start_date=20250523T063605, end_date=20250523T063629
[2025-05-23T06:36:29.741+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task Transform_Data (Bash command failed. The command returned a non-zero exit code 1.; 7603)
[2025-05-23T06:36:29.768+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-23T06:36:29.798+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
