[2025-05-22T17:51:18.086+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Extract_Data scheduled__2025-05-22T17:30:00+00:00 [queued]>
[2025-05-22T17:51:18.096+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Extract_Data scheduled__2025-05-22T17:30:00+00:00 [queued]>
[2025-05-22T17:51:18.096+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-22T17:51:18.110+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Extract_Data> on 2025-05-22 17:30:00+00:00
[2025-05-22T17:51:18.115+0000] {standard_task_runner.py:57} INFO - Started process 245 to run task
[2025-05-22T17:51:18.121+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Extract_Data', 'scheduled__2025-05-22T17:30:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmpe2g1ru16']
[2025-05-22T17:51:18.126+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask Extract_Data
[2025-05-22T17:51:18.180+0000] {task_command.py:416} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Extract_Data scheduled__2025-05-22T17:30:00+00:00 [running]> on host 2d3af573cb97
[2025-05-22T17:51:18.249+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Scheduler_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Extract_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T17:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T17:30:00+00:00'
[2025-05-22T17:51:18.251+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T17:51:18.252+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Extract_Data.py']
[2025-05-22T17:51:18.261+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T17:51:20.945+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T17:51:20.946+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T17:51:20.947+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T17:51:20.947+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T17:51:20.948+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T17:51:21.131+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T17:51:21.236+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T17:51:21.236+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T17:51:21.240+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T17:51:21.241+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-bacde983-04b8-4f00-8621-50f672ed0daa;1.0
[2025-05-22T17:51:21.242+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T17:51:23.749+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T17:51:25.737+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar ...
[2025-05-22T17:51:27.204+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 4494ms :: artifacts dl 1468ms
[2025-05-22T17:51:27.204+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T17:51:27.205+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T17:51:27.205+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T17:51:27.206+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T17:51:27.206+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T17:51:27.207+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T17:51:27.207+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   1   |   1   |   0   ||   1   |   0   |
[2025-05-22T17:51:27.208+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T17:51:27.208+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.209+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-05-22T17:51:27.209+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-05-22T17:51:27.210+0000] {subprocess.py:93} INFO - 	problem while downloading module descriptor: https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom: Downloaded file size doesn't match expected Content Length for https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom. Please retry. (250ms)
[2025-05-22T17:51:27.210+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.211+0000] {subprocess.py:93} INFO - 		module not found: org.checkerframework#checker-qual;3.31.0
[2025-05-22T17:51:27.211+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.212+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-05-22T17:51:27.212+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.213+0000] {subprocess.py:93} INFO - 	  file:/home/***/.m2/repository/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom
[2025-05-22T17:51:27.213+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.214+0000] {subprocess.py:93} INFO - 	  -- artifact org.checkerframework#checker-qual;3.31.0!checker-qual.jar:
[2025-05-22T17:51:27.214+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.215+0000] {subprocess.py:93} INFO - 	  file:/home/***/.m2/repository/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar
[2025-05-22T17:51:27.216+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.216+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-05-22T17:51:27.217+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.217+0000] {subprocess.py:93} INFO - 	  /home/***/.ivy2/local/org.checkerframework/checker-qual/3.31.0/ivys/ivy.xml
[2025-05-22T17:51:27.218+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.218+0000] {subprocess.py:93} INFO - 	  -- artifact org.checkerframework#checker-qual;3.31.0!checker-qual.jar:
[2025-05-22T17:51:27.219+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.220+0000] {subprocess.py:93} INFO - 	  /home/***/.ivy2/local/org.checkerframework/checker-qual/3.31.0/jars/checker-qual.jar
[2025-05-22T17:51:27.220+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.221+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-05-22T17:51:27.221+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.222+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom
[2025-05-22T17:51:27.223+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.223+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-05-22T17:51:27.224+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.224+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom
[2025-05-22T17:51:27.225+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.225+0000] {subprocess.py:93} INFO - 	  -- artifact org.checkerframework#checker-qual;3.31.0!checker-qual.jar:
[2025-05-22T17:51:27.226+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.226+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar
[2025-05-22T17:51:27.227+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.227+0000] {subprocess.py:93} INFO - 		[FAILED     ] org.postgresql#postgresql;42.6.0!postgresql.jar: Downloaded file size doesn't match expected Content Length for https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar. Please retry. (1466ms)
[2025-05-22T17:51:27.228+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.228+0000] {subprocess.py:93} INFO - 		[FAILED     ] org.postgresql#postgresql;42.6.0!postgresql.jar: Downloaded file size doesn't match expected Content Length for https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar. Please retry. (1466ms)
[2025-05-22T17:51:27.229+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.230+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-05-22T17:51:27.230+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.231+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar
[2025-05-22T17:51:27.231+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.232+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T17:51:27.232+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.233+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-05-22T17:51:27.233+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.234+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T17:51:27.234+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.235+0000] {subprocess.py:93} INFO - 		:: org.checkerframework#checker-qual;3.31.0: not found
[2025-05-22T17:51:27.235+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.236+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T17:51:27.237+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.237+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.237+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T17:51:27.238+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.239+0000] {subprocess.py:93} INFO - 		::              FAILED DOWNLOADS            ::
[2025-05-22T17:51:27.239+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.239+0000] {subprocess.py:93} INFO - 		:: ^ see resolution messages for details  ^ ::
[2025-05-22T17:51:27.240+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.240+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T17:51:27.241+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.241+0000] {subprocess.py:93} INFO - 		:: org.postgresql#postgresql;42.6.0!postgresql.jar
[2025-05-22T17:51:27.242+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.242+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T17:51:27.243+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.243+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.244+0000] {subprocess.py:93} INFO - 
[2025-05-22T17:51:27.244+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-05-22T17:51:27.244+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.checkerframework#checker-qual;3.31.0: not found, download failed: org.postgresql#postgresql;42.6.0!postgresql.jar]
[2025-05-22T17:51:27.245+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1429)
[2025-05-22T17:51:27.245+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
[2025-05-22T17:51:27.246+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-05-22T17:51:27.246+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
[2025-05-22T17:51:27.247+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-05-22T17:51:27.248+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-05-22T17:51:27.248+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-05-22T17:51:27.249+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
[2025-05-22T17:51:27.249+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
[2025-05-22T17:51:27.250+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-05-22T17:51:27.255+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-22T17:51:27.255+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/Extract_Data.py", line 10, in <module>
[2025-05-22T17:51:27.261+0000] {subprocess.py:93} INFO -     .getOrCreate()
[2025-05-22T17:51:27.261+0000] {subprocess.py:93} INFO -      ^^^^^^^^^^^^^
[2025-05-22T17:51:27.262+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2025-05-22T17:51:27.262+0000] {subprocess.py:93} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-05-22T17:51:27.263+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-22T17:51:27.263+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/context.py", line 384, in getOrCreate
[2025-05-22T17:51:27.264+0000] {subprocess.py:93} INFO -     SparkContext(conf=conf or SparkConf())
[2025-05-22T17:51:27.264+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/context.py", line 144, in __init__
[2025-05-22T17:51:27.265+0000] {subprocess.py:93} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-05-22T17:51:27.266+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/context.py", line 331, in _ensure_initialized
[2025-05-22T17:51:27.266+0000] {subprocess.py:93} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-05-22T17:51:27.269+0000] {subprocess.py:93} INFO -                                        ^^^^^^^^^^^^^^^^^^^^
[2025-05-22T17:51:27.269+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2025-05-22T17:51:27.270+0000] {subprocess.py:93} INFO -     raise Exception("Java gateway process exited before sending its port number")
[2025-05-22T17:51:27.271+0000] {subprocess.py:93} INFO - Exception: Java gateway process exited before sending its port number
[2025-05-22T17:51:27.381+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-22T17:51:27.391+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T17:51:27.395+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Extract_Data, execution_date=20250522T173000, start_date=20250522T175118, end_date=20250522T175127
[2025-05-22T17:51:27.410+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task Extract_Data (Bash command failed. The command returned a non-zero exit code 1.; 245)
[2025-05-22T17:51:27.431+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-22T17:51:27.453+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
