[2025-05-22T16:18:48.385+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Datamart_Traffict_Accident.Extract_Datamart_Data scheduled__2025-05-22T16:00:00+00:00 [queued]>
[2025-05-22T16:18:48.396+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Datamart_Traffict_Accident.Extract_Datamart_Data scheduled__2025-05-22T16:00:00+00:00 [queued]>
[2025-05-22T16:18:48.397+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-22T16:18:48.411+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Extract_Datamart_Data> on 2025-05-22 16:00:00+00:00
[2025-05-22T16:18:48.418+0000] {standard_task_runner.py:57} INFO - Started process 255 to run task
[2025-05-22T16:18:48.421+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Datamart_Traffict_Accident', 'Extract_Datamart_Data', 'scheduled__2025-05-22T16:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/Datamart_Traffict_Accident.py', '--cfg-path', '/tmp/tmps9gsnjh6']
[2025-05-22T16:18:48.425+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask Extract_Datamart_Data
[2025-05-22T16:18:48.484+0000] {task_command.py:416} INFO - Running <TaskInstance: Datamart_Traffict_Accident.Extract_Datamart_Data scheduled__2025-05-22T16:00:00+00:00 [running]> on host 37de2a8083a6
[2025-05-22T16:18:48.565+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Datamart_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Extract_Datamart_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T16:00:00+00:00'
[2025-05-22T16:18:48.567+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T16:18:48.568+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Extract_Datamart_Data.py']
[2025-05-22T16:18:48.578+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T16:18:50.468+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T16:18:50.469+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T16:18:50.469+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T16:18:50.470+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T16:18:50.470+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T16:18:50.633+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T16:18:50.719+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T16:18:50.720+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T16:18:50.723+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T16:18:50.724+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-3f42108c-63f6-479f-881f-49578d88cd7f;1.0
[2025-05-22T16:18:50.725+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T16:18:53.298+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T16:18:55.328+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar ...
[2025-05-22T16:18:56.763+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 4602ms :: artifacts dl 1436ms
[2025-05-22T16:18:56.764+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T16:18:56.765+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T16:18:56.765+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:18:56.766+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T16:18:56.767+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T16:18:56.768+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:18:56.768+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   1   |   1   |   0   ||   1   |   0   |
[2025-05-22T16:18:56.769+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T16:18:56.770+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.771+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-05-22T16:18:56.771+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-05-22T16:18:56.771+0000] {subprocess.py:93} INFO - 	problem while downloading module descriptor: https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom: Downloaded file size doesn't match expected Content Length for https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom. Please retry. (258ms)
[2025-05-22T16:18:56.772+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.774+0000] {subprocess.py:93} INFO - 		module not found: org.checkerframework#checker-qual;3.31.0
[2025-05-22T16:18:56.774+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.776+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-05-22T16:18:56.777+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.778+0000] {subprocess.py:93} INFO - 	  file:/home/***/.m2/repository/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom
[2025-05-22T16:18:56.779+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.780+0000] {subprocess.py:93} INFO - 	  -- artifact org.checkerframework#checker-qual;3.31.0!checker-qual.jar:
[2025-05-22T16:18:56.781+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.781+0000] {subprocess.py:93} INFO - 	  file:/home/***/.m2/repository/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar
[2025-05-22T16:18:56.782+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.782+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-05-22T16:18:56.783+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.784+0000] {subprocess.py:93} INFO - 	  /home/***/.ivy2/local/org.checkerframework/checker-qual/3.31.0/ivys/ivy.xml
[2025-05-22T16:18:56.784+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.785+0000] {subprocess.py:93} INFO - 	  -- artifact org.checkerframework#checker-qual;3.31.0!checker-qual.jar:
[2025-05-22T16:18:56.785+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.786+0000] {subprocess.py:93} INFO - 	  /home/***/.ivy2/local/org.checkerframework/checker-qual/3.31.0/jars/checker-qual.jar
[2025-05-22T16:18:56.786+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.787+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-05-22T16:18:56.787+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.787+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom
[2025-05-22T16:18:56.788+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.788+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-05-22T16:18:56.789+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.789+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.pom
[2025-05-22T16:18:56.790+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.791+0000] {subprocess.py:93} INFO - 	  -- artifact org.checkerframework#checker-qual;3.31.0!checker-qual.jar:
[2025-05-22T16:18:56.791+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.792+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar
[2025-05-22T16:18:56.793+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.794+0000] {subprocess.py:93} INFO - 		[FAILED     ] org.postgresql#postgresql;42.6.0!postgresql.jar: Downloaded file size doesn't match expected Content Length for https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar. Please retry. (1434ms)
[2025-05-22T16:18:56.795+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.795+0000] {subprocess.py:93} INFO - 		[FAILED     ] org.postgresql#postgresql;42.6.0!postgresql.jar: Downloaded file size doesn't match expected Content Length for https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar. Please retry. (1434ms)
[2025-05-22T16:18:56.796+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.796+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-05-22T16:18:56.797+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.798+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar
[2025-05-22T16:18:56.798+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.799+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T16:18:56.799+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.800+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-05-22T16:18:56.801+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.801+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T16:18:56.802+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.802+0000] {subprocess.py:93} INFO - 		:: org.checkerframework#checker-qual;3.31.0: not found
[2025-05-22T16:18:56.803+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.803+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T16:18:56.804+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.804+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.805+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T16:18:56.806+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.806+0000] {subprocess.py:93} INFO - 		::              FAILED DOWNLOADS            ::
[2025-05-22T16:18:56.807+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.807+0000] {subprocess.py:93} INFO - 		:: ^ see resolution messages for details  ^ ::
[2025-05-22T16:18:56.808+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.808+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T16:18:56.809+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.809+0000] {subprocess.py:93} INFO - 		:: org.postgresql#postgresql;42.6.0!postgresql.jar
[2025-05-22T16:18:56.810+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.811+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-22T16:18:56.812+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.813+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.813+0000] {subprocess.py:93} INFO - 
[2025-05-22T16:18:56.814+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-05-22T16:18:56.815+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.checkerframework#checker-qual;3.31.0: not found, download failed: org.postgresql#postgresql;42.6.0!postgresql.jar]
[2025-05-22T16:18:56.815+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1429)
[2025-05-22T16:18:56.816+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
[2025-05-22T16:18:56.817+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-05-22T16:18:56.817+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
[2025-05-22T16:18:56.818+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-05-22T16:18:56.819+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-05-22T16:18:56.819+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-05-22T16:18:56.820+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
[2025-05-22T16:18:56.821+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
[2025-05-22T16:18:56.821+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-05-22T16:18:56.843+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-22T16:18:56.844+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/Extract_Datamart_Data.py", line 9, in <module>
[2025-05-22T16:18:56.850+0000] {subprocess.py:93} INFO -     .getOrCreate()
[2025-05-22T16:18:56.850+0000] {subprocess.py:93} INFO -      ^^^^^^^^^^^^^
[2025-05-22T16:18:56.851+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2025-05-22T16:18:56.852+0000] {subprocess.py:93} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-05-22T16:18:56.852+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-22T16:18:56.853+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/context.py", line 384, in getOrCreate
[2025-05-22T16:18:56.854+0000] {subprocess.py:93} INFO -     SparkContext(conf=conf or SparkConf())
[2025-05-22T16:18:56.855+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/context.py", line 144, in __init__
[2025-05-22T16:18:56.856+0000] {subprocess.py:93} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-05-22T16:18:56.857+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/context.py", line 331, in _ensure_initialized
[2025-05-22T16:18:56.858+0000] {subprocess.py:93} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-05-22T16:18:56.859+0000] {subprocess.py:93} INFO -                                        ^^^^^^^^^^^^^^^^^^^^
[2025-05-22T16:18:56.859+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2025-05-22T16:18:56.860+0000] {subprocess.py:93} INFO -     raise Exception("Java gateway process exited before sending its port number")
[2025-05-22T16:18:56.861+0000] {subprocess.py:93} INFO - Exception: Java gateway process exited before sending its port number
[2025-05-22T16:18:56.906+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-22T16:18:56.920+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T16:18:56.924+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Datamart_Traffict_Accident, task_id=Extract_Datamart_Data, execution_date=20250522T160000, start_date=20250522T161848, end_date=20250522T161856
[2025-05-22T16:18:56.947+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task Extract_Datamart_Data (Bash command failed. The command returned a non-zero exit code 1.; 255)
[2025-05-22T16:18:56.983+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-22T16:18:57.017+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
