[2025-05-22T15:30:51.757+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-22T15:15:00+00:00 [queued]>
[2025-05-22T15:30:51.768+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-22T15:15:00+00:00 [queued]>
[2025-05-22T15:30:51.769+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-22T15:30:51.785+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Load_Data> on 2025-05-22 15:15:00+00:00
[2025-05-22T15:30:51.792+0000] {standard_task_runner.py:57} INFO - Started process 2424 to run task
[2025-05-22T15:30:51.795+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Load_Data', 'scheduled__2025-05-22T15:15:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmptvn804l7']
[2025-05-22T15:30:51.799+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask Load_Data
[2025-05-22T15:30:51.850+0000] {task_command.py:416} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Load_Data scheduled__2025-05-22T15:15:00+00:00 [running]> on host 68da71f009b0
[2025-05-22T15:30:51.941+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Scheduler_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Load_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T15:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T15:15:00+00:00'
[2025-05-22T15:30:51.943+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T15:30:51.945+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Load_Data.py']
[2025-05-22T15:30:51.956+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T15:30:53.816+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T15:30:53.817+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T15:30:53.819+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T15:30:53.820+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T15:30:53.821+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T15:30:53.976+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T15:30:54.072+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T15:30:54.073+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T15:30:54.077+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T15:30:54.078+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-805a1002-ea8f-421f-b529-e5e060bbf83b;1.0
[2025-05-22T15:30:54.078+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T15:30:54.192+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T15:30:54.217+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-22T15:30:54.238+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 153ms :: artifacts dl 7ms
[2025-05-22T15:30:54.240+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T15:30:54.240+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-22T15:30:54.241+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T15:30:54.241+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:30:54.242+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T15:30:54.243+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T15:30:54.243+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:30:54.244+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-22T15:30:54.245+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:30:54.245+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-805a1002-ea8f-421f-b529-e5e060bbf83b
[2025-05-22T15:30:54.246+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T15:30:54.248+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 2 already retrieved (0kB/5ms)
[2025-05-22T15:30:54.456+0000] {subprocess.py:93} INFO - 25/05/22 15:30:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-22T15:30:54.739+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-22T15:30:54.740+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-22T15:30:54.741+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-22T15:31:05.156+0000] {subprocess.py:93} INFO - [Stage 6:>                                                          (0 + 1) / 1]25/05/22 15:31:05 ERROR Executor: Exception in task 0.0 in stage 6.0 (TID 15)
[2025-05-22T15:31:05.157+0000] {subprocess.py:93} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:05.158+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:05.160+0000] {subprocess.py:93} INFO -   Position: 71  Call getNextException to see other errors in the batch.
[2025-05-22T15:31:05.161+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:31:05.162+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-22T15:31:05.163+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:31:05.164+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:31:05.165+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:31:05.167+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:31:05.168+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:31:05.169+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:31:05.170+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:31:05.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:31:05.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:31:05.172+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:31:05.173+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:31:05.174+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:31:05.175+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:31:05.175+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:31:05.176+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:31:05.176+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:31:05.177+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:05.178+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:05.179+0000] {subprocess.py:93} INFO -   Position: 71
[2025-05-22T15:31:05.180+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:31:05.181+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:31:05.181+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-22T15:31:05.182+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-22T15:31:05.183+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-22T15:31:05.183+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-05-22T15:31:05.204+0000] {subprocess.py:93} INFO - 25/05/22 15:31:05 WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 15) (68da71f009b0 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:05.205+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:05.205+0000] {subprocess.py:93} INFO -   Position: 71  Call getNextException to see other errors in the batch.
[2025-05-22T15:31:05.206+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:31:05.207+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-22T15:31:05.208+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:31:05.210+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:31:05.211+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:31:05.211+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:31:05.212+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:31:05.213+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:31:05.213+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:31:05.214+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:31:05.215+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:31:05.216+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:31:05.217+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:31:05.217+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:31:05.218+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:31:05.219+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:31:05.219+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:31:05.220+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:31:05.221+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:05.221+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:05.222+0000] {subprocess.py:93} INFO -   Position: 71
[2025-05-22T15:31:05.222+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:31:05.223+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:31:05.225+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-22T15:31:05.226+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-22T15:31:05.226+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-22T15:31:05.227+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-05-22T15:31:05.228+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:31:05.228+0000] {subprocess.py:93} INFO - 25/05/22 15:31:05 ERROR TaskSetManager: Task 0 in stage 6.0 failed 1 times; aborting job
[2025-05-22T15:31:05.321+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-22T15:31:05.322+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/Load_Data.py", line 21, in <module>
[2025-05-22T15:31:05.327+0000] {subprocess.py:93} INFO -     data_date.write.jdbc(url=postgres_url, table="date", mode="append", properties=postgres_properties)
[2025-05-22T15:31:05.329+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 1445, in jdbc
[2025-05-22T15:31:05.331+0000] {subprocess.py:93} INFO -     self.mode(mode)._jwrite.jdbc(url, table, jprop)
[2025-05-22T15:31:05.332+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1304, in __call__
[2025-05-22T15:31:05.333+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-22T15:31:05.334+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^
[2025-05-22T15:31:05.335+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 111, in deco
[2025-05-22T15:31:05.336+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-22T15:31:05.337+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2025-05-22T15:31:05.337+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/protocol.py", line 326, in get_return_value
[2025-05-22T15:31:05.338+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-22T15:31:05.375+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o53.jdbc.
[2025-05-22T15:31:05.376+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6.0 (TID 15) (68da71f009b0 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:05.377+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:05.378+0000] {subprocess.py:93} INFO -   Position: 71  Call getNextException to see other errors in the batch.
[2025-05-22T15:31:05.378+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:31:05.379+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-22T15:31:05.379+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:31:05.379+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:31:05.380+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:31:05.380+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:31:05.381+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:31:05.381+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:31:05.381+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:31:05.382+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:31:05.382+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:31:05.382+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:31:05.383+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:31:05.384+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:31:05.384+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:31:05.385+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:31:05.385+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:31:05.386+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:31:05.386+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:05.386+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:05.387+0000] {subprocess.py:93} INFO -   Position: 71
[2025-05-22T15:31:05.387+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:31:05.388+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:31:05.389+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-22T15:31:05.390+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-22T15:31:05.391+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-22T15:31:05.391+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-05-22T15:31:05.393+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:31:05.393+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-05-22T15:31:05.393+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
[2025-05-22T15:31:05.394+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
[2025-05-22T15:31:05.394+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
[2025-05-22T15:31:05.395+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-22T15:31:05.395+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-22T15:31:05.396+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-22T15:31:05.396+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
[2025-05-22T15:31:05.397+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
[2025-05-22T15:31:05.397+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
[2025-05-22T15:31:05.398+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-05-22T15:31:05.398+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
[2025-05-22T15:31:05.399+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
[2025-05-22T15:31:05.399+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
[2025-05-22T15:31:05.399+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
[2025-05-22T15:31:05.400+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-05-22T15:31:05.400+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
[2025-05-22T15:31:05.400+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
[2025-05-22T15:31:05.401+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
[2025-05-22T15:31:05.401+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
[2025-05-22T15:31:05.402+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
[2025-05-22T15:31:05.403+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
[2025-05-22T15:31:05.403+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-22T15:31:05.404+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-05-22T15:31:05.405+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
[2025-05-22T15:31:05.405+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
[2025-05-22T15:31:05.405+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:854)
[2025-05-22T15:31:05.406+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:68)
[2025-05-22T15:31:05.406+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
[2025-05-22T15:31:05.407+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
[2025-05-22T15:31:05.407+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
[2025-05-22T15:31:05.407+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
[2025-05-22T15:31:05.408+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
[2025-05-22T15:31:05.408+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
[2025-05-22T15:31:05.409+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-22T15:31:05.409+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
[2025-05-22T15:31:05.410+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
[2025-05-22T15:31:05.410+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
[2025-05-22T15:31:05.411+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
[2025-05-22T15:31:05.411+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
[2025-05-22T15:31:05.411+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
[2025-05-22T15:31:05.412+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
[2025-05-22T15:31:05.412+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
[2025-05-22T15:31:05.412+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
[2025-05-22T15:31:05.413+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
[2025-05-22T15:31:05.413+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
[2025-05-22T15:31:05.414+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
[2025-05-22T15:31:05.415+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
[2025-05-22T15:31:05.415+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
[2025-05-22T15:31:05.416+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:817)
[2025-05-22T15:31:05.416+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-22T15:31:05.417+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-22T15:31:05.417+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-22T15:31:05.417+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-22T15:31:05.418+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-22T15:31:05.418+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-22T15:31:05.418+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-22T15:31:05.419+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-22T15:31:05.419+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-22T15:31:05.420+0000] {subprocess.py:93} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2025-05-22T15:31:05.420+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:31:05.420+0000] {subprocess.py:93} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:05.421+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:05.421+0000] {subprocess.py:93} INFO -   Position: 71  Call getNextException to see other errors in the batch.
[2025-05-22T15:31:05.422+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:31:05.422+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-22T15:31:05.423+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:31:05.423+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:31:05.424+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:31:05.424+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:31:05.425+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:31:05.425+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:31:05.426+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:31:05.426+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:31:05.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:31:05.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:31:05.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:31:05.428+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:31:05.428+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:31:05.429+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:31:05.429+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:31:05.430+0000] {subprocess.py:93} INFO - 	... 1 more
[2025-05-22T15:31:05.430+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:05.431+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:05.431+0000] {subprocess.py:93} INFO -   Position: 71
[2025-05-22T15:31:05.432+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:31:05.432+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:31:05.432+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-22T15:31:05.433+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-22T15:31:05.433+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-22T15:31:05.434+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-05-22T15:31:05.434+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:31:05.849+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-22T15:31:05.863+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T15:31:05.869+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Load_Data, execution_date=20250522T151500, start_date=20250522T153051, end_date=20250522T153105
[2025-05-22T15:31:05.888+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task Load_Data (Bash command failed. The command returned a non-zero exit code 1.; 2424)
[2025-05-22T15:31:05.910+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-22T15:31:05.939+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
