[2025-05-22T15:31:17.199+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [queued]>
[2025-05-22T15:31:17.209+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [queued]>
[2025-05-22T15:31:17.210+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 4
[2025-05-22T15:31:17.227+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Load_Data> on 2025-05-22 15:17:26.089500+00:00
[2025-05-22T15:31:17.237+0000] {standard_task_runner.py:57} INFO - Started process 2737 to run task
[2025-05-22T15:31:17.241+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Scheduler_Traffict_Accident', 'Load_Data', 'manual__2025-05-22T15:17:26.089500+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/Scheduler_Traffict_Accident.py', '--cfg-path', '/tmp/tmpm2rw5zz8']
[2025-05-22T15:31:17.246+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask Load_Data
[2025-05-22T15:31:17.302+0000] {task_command.py:416} INFO - Running <TaskInstance: Scheduler_Traffict_Accident.Load_Data manual__2025-05-22T15:17:26.089500+00:00 [running]> on host 68da71f009b0
[2025-05-22T15:31:17.396+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hisham' AIRFLOW_CTX_DAG_ID='Scheduler_Traffict_Accident' AIRFLOW_CTX_TASK_ID='Load_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T15:17:26.089500+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T15:17:26.089500+00:00'
[2025-05-22T15:31:17.398+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T15:31:17.401+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/scripts/Load_Data.py']
[2025-05-22T15:31:17.414+0000] {subprocess.py:86} INFO - Output:
[2025-05-22T15:31:19.153+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2025-05-22T15:31:19.154+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-05-22T15:31:19.155+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-05-22T15:31:19.156+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-05-22T15:31:19.156+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-05-22T15:31:19.312+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-22T15:31:19.406+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-05-22T15:31:19.407+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-05-22T15:31:19.411+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-05-22T15:31:19.413+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-780aaab4-941b-4665-871b-d3f1dcfc4c78;1.0
[2025-05-22T15:31:19.414+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T15:31:19.521+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-05-22T15:31:19.547+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-05-22T15:31:19.564+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 146ms :: artifacts dl 5ms
[2025-05-22T15:31:19.565+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-22T15:31:19.566+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-05-22T15:31:19.566+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-05-22T15:31:19.567+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:31:19.567+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-22T15:31:19.568+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-22T15:31:19.568+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:31:19.569+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-05-22T15:31:19.569+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-22T15:31:19.569+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-780aaab4-941b-4665-871b-d3f1dcfc4c78
[2025-05-22T15:31:19.570+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-22T15:31:19.574+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 2 already retrieved (0kB/4ms)
[2025-05-22T15:31:19.775+0000] {subprocess.py:93} INFO - 25/05/22 15:31:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-22T15:31:20.062+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-05-22T15:31:20.063+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-22T15:31:20.063+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-22T15:31:29.634+0000] {subprocess.py:93} INFO - [Stage 5:=====>                                                    (1 + 9) / 10]                                                                                [Stage 6:>                                                          (0 + 1) / 1]25/05/22 15:31:29 ERROR Executor: Exception in task 0.0 in stage 6.0 (TID 15)
[2025-05-22T15:31:29.636+0000] {subprocess.py:93} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:29.638+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:29.639+0000] {subprocess.py:93} INFO -   Position: 71  Call getNextException to see other errors in the batch.
[2025-05-22T15:31:29.640+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:31:29.641+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-22T15:31:29.642+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:31:29.643+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:31:29.644+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:31:29.645+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:31:29.646+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:31:29.647+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:31:29.647+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:31:29.648+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:31:29.649+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:31:29.650+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:31:29.651+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:31:29.652+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:31:29.652+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:31:29.653+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:31:29.654+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:31:29.655+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:31:29.655+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:29.656+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:29.657+0000] {subprocess.py:93} INFO -   Position: 71
[2025-05-22T15:31:29.659+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:31:29.660+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:31:29.661+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-22T15:31:29.662+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-22T15:31:29.662+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-22T15:31:29.663+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-05-22T15:31:29.691+0000] {subprocess.py:93} INFO - 25/05/22 15:31:29 WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 15) (68da71f009b0 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:29.692+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:29.693+0000] {subprocess.py:93} INFO -   Position: 71  Call getNextException to see other errors in the batch.
[2025-05-22T15:31:29.693+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:31:29.694+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-22T15:31:29.695+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:31:29.696+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:31:29.697+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:31:29.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:31:29.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:31:29.700+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:31:29.702+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:31:29.703+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:31:29.704+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:31:29.705+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:31:29.706+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:31:29.707+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:31:29.708+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:31:29.709+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:31:29.709+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:31:29.710+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:31:29.710+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:29.711+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:29.712+0000] {subprocess.py:93} INFO -   Position: 71
[2025-05-22T15:31:29.713+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:31:29.713+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:31:29.714+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-22T15:31:29.715+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-22T15:31:29.715+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-22T15:31:29.716+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-05-22T15:31:29.717+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:31:29.717+0000] {subprocess.py:93} INFO - 25/05/22 15:31:29 ERROR TaskSetManager: Task 0 in stage 6.0 failed 1 times; aborting job
[2025-05-22T15:31:29.831+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-22T15:31:29.833+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/Load_Data.py", line 21, in <module>
[2025-05-22T15:31:29.841+0000] {subprocess.py:93} INFO -     data_date.write.jdbc(url=postgres_url, table="date", mode="append", properties=postgres_properties)
[2025-05-22T15:31:29.844+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 1445, in jdbc
[2025-05-22T15:31:29.845+0000] {subprocess.py:93} INFO -     self.mode(mode)._jwrite.jdbc(url, table, jprop)
[2025-05-22T15:31:29.846+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1304, in __call__
[2025-05-22T15:31:29.847+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-22T15:31:29.848+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^
[2025-05-22T15:31:29.849+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 111, in deco
[2025-05-22T15:31:29.850+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-22T15:31:29.851+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2025-05-22T15:31:29.851+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/protocol.py", line 326, in get_return_value
[2025-05-22T15:31:29.852+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-22T15:31:29.894+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o53.jdbc.
[2025-05-22T15:31:29.895+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6.0 (TID 15) (68da71f009b0 executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:29.896+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:29.897+0000] {subprocess.py:93} INFO -   Position: 71  Call getNextException to see other errors in the batch.
[2025-05-22T15:31:29.897+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:31:29.898+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-22T15:31:29.899+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:31:29.900+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:31:29.901+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:31:29.902+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:31:29.903+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:31:29.904+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:31:29.905+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:31:29.907+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:31:29.908+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:31:29.909+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:31:29.911+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:31:29.912+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:31:29.913+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:31:29.914+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:31:29.915+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:31:29.915+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:31:29.916+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:29.918+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:29.919+0000] {subprocess.py:93} INFO -   Position: 71
[2025-05-22T15:31:29.919+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:31:29.920+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:31:29.921+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-22T15:31:29.924+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-22T15:31:29.926+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-22T15:31:29.927+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-05-22T15:31:29.928+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:31:29.929+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-05-22T15:31:29.930+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
[2025-05-22T15:31:29.931+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
[2025-05-22T15:31:29.932+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
[2025-05-22T15:31:29.933+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-22T15:31:29.934+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-22T15:31:29.935+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-22T15:31:29.936+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
[2025-05-22T15:31:29.937+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
[2025-05-22T15:31:29.939+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
[2025-05-22T15:31:29.940+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-05-22T15:31:29.941+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
[2025-05-22T15:31:29.943+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
[2025-05-22T15:31:29.944+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
[2025-05-22T15:31:29.945+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
[2025-05-22T15:31:29.946+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-05-22T15:31:29.948+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
[2025-05-22T15:31:29.949+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
[2025-05-22T15:31:29.951+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
[2025-05-22T15:31:29.952+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
[2025-05-22T15:31:29.953+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
[2025-05-22T15:31:29.954+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
[2025-05-22T15:31:29.955+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-22T15:31:29.957+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-05-22T15:31:29.958+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
[2025-05-22T15:31:29.959+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
[2025-05-22T15:31:29.961+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:854)
[2025-05-22T15:31:29.962+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:68)
[2025-05-22T15:31:29.964+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
[2025-05-22T15:31:29.965+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
[2025-05-22T15:31:29.967+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
[2025-05-22T15:31:29.968+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
[2025-05-22T15:31:29.969+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
[2025-05-22T15:31:29.971+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
[2025-05-22T15:31:29.972+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-05-22T15:31:29.973+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
[2025-05-22T15:31:29.974+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
[2025-05-22T15:31:29.976+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
[2025-05-22T15:31:29.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
[2025-05-22T15:31:29.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
[2025-05-22T15:31:29.979+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
[2025-05-22T15:31:29.980+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
[2025-05-22T15:31:29.981+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
[2025-05-22T15:31:29.982+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
[2025-05-22T15:31:29.983+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
[2025-05-22T15:31:29.984+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
[2025-05-22T15:31:29.985+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
[2025-05-22T15:31:29.986+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
[2025-05-22T15:31:29.987+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
[2025-05-22T15:31:29.988+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:817)
[2025-05-22T15:31:29.990+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-22T15:31:29.991+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-22T15:31:29.991+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-22T15:31:29.992+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-22T15:31:29.993+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-22T15:31:29.994+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-22T15:31:29.995+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-22T15:31:29.996+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-22T15:31:29.996+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-22T15:31:29.997+0000] {subprocess.py:93} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2025-05-22T15:31:29.998+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T15:31:29.998+0000] {subprocess.py:93} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO date ("date","year","month","day_of_week","week") VALUES ('2013-03-01',2013,3,6,1) was aborted: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:29.999+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:30.000+0000] {subprocess.py:93} INFO -   Position: 71  Call getNextException to see other errors in the batch.
[2025-05-22T15:31:30.001+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
[2025-05-22T15:31:30.002+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:880)
[2025-05-22T15:31:30.003+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
[2025-05-22T15:31:30.003+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
[2025-05-22T15:31:30.004+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:687)
[2025-05-22T15:31:30.005+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
[2025-05-22T15:31:30.006+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
[2025-05-22T15:31:30.006+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
[2025-05-22T15:31:30.007+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
[2025-05-22T15:31:30.008+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
[2025-05-22T15:31:30.009+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2025-05-22T15:31:30.009+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2025-05-22T15:31:30.010+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2025-05-22T15:31:30.011+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2025-05-22T15:31:30.012+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2025-05-22T15:31:30.013+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-05-22T15:31:30.013+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-05-22T15:31:30.014+0000] {subprocess.py:93} INFO - 	... 1 more
[2025-05-22T15:31:30.015+0000] {subprocess.py:93} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: column "date" is of type date but expression is of type character varying
[2025-05-22T15:31:30.015+0000] {subprocess.py:93} INFO -   Hint: You will need to rewrite or cast the expression.
[2025-05-22T15:31:30.015+0000] {subprocess.py:93} INFO -   Position: 71
[2025-05-22T15:31:30.016+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[2025-05-22T15:31:30.017+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[2025-05-22T15:31:30.018+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[2025-05-22T15:31:30.019+0000] {subprocess.py:93} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[2025-05-22T15:31:30.019+0000] {subprocess.py:93} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:877)
[2025-05-22T15:31:30.020+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-05-22T15:31:30.021+0000] {subprocess.py:93} INFO - 
[2025-05-22T15:31:30.423+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-22T15:31:30.449+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T15:31:30.458+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Scheduler_Traffict_Accident, task_id=Load_Data, execution_date=20250522T151726, start_date=20250522T153117, end_date=20250522T153130
[2025-05-22T15:31:30.483+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task Load_Data (Bash command failed. The command returned a non-zero exit code 1.; 2737)
[2025-05-22T15:31:30.530+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-22T15:31:30.557+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
